###################
### Build Steps ###
###################
steps:

  ##########################
  ### Build docker image ###
  ##########################
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/antonia', '.' ]

  #####################################
  ### Push docker image to registry ###
  #####################################
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/antonia' ]

############
### Tags ###
############
tags: [ 'antonia' ]

#################
### Artifacts ###
#################
images: [ 'gcr.io/$PROJECT_ID/antonia' ]
